[workspace]
resolver = "3"
members = [
    "crates/dust-compiler",
    "crates/dust-ast",
    "crates/dust-ast-print",
    "crates/dust-hir",
    "crates/dust-interpretter",
    "crates/dust-lexer",
    "crates/dust-print",
    "crates/dust-utils", "crates/dust-ast-lowering", "crates/dust-ctxt",
]

[workspace.dependencies]
dust-lexer = { path = "crates/dust-lexer" }
dust-ast = { path = "crates/dust-ast" }
dust-ast-lowering = {path = "crates/dust-ast-lowering/"}
dust-ast-print = { path = "crates/dust-ast-print" }
dust-print = { path = "crates/dust-print" }
dust-hir = { path = "crates/dust-hir" }
dust-interpretter = { path = "crates/dust-interpretter/" }
dust-ctxt = { path = "crates/dust-ctxt/" }
utils = { package = "dust-utils", path = "crates/dust-utils" }

bumpalo = {version = "3.20", features = ["allocator_api", "serde", "boxed"]}
string-interner = "0.20"
ahash = "0.8"

miette = { version = "7.6", features = ["fancy", "serde"] }
camino = "1.2"



insta = {version = "1.48", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
