[package]
name = "dust-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
dust-interpretter.workspace = true

dust-lexer.workspace = true
dust-ast.workspace = true
dust-ast-lowering.workspace = true
dust-ast-print.workspace = true
dust-hir.workspace = true
dust-ctxt.workspace = true
utils.workspace = true

miette = { version = "7.6", features = ["fancy"] }
clap = { version = "4.5", features = ["derive"] }

camino.workspace = true
